# Generated by Django 4.2 on 2023-10-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoverunder15',
            name='value',
            field=models.CharField(choices=[(0, 'null'), (1, 'Over'), (2, 'Under')], max_length=30),
        ),
    ]
