# Generated by Django 4.2 on 2023-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gameoverunder15_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoverunder15',
            name='value',
            field=models.IntegerField(choices=[(0, 'null'), (1, 'Over'), (2, 'Under')]),
        ),
    ]
