# Generated by Django 4.2 on 2023-05-01 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AddField(
            model_name='game',
            name='game_month',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)]),
        ),
        migrations.AddField(
            model_name='game',
            name='game_year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
