# Generated by Django 4.2 on 2023-05-02 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_game_date_game_game_month_game_game_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.competition'),
        ),
    ]
