# Generated by Django 4.2 on 2023-05-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_game_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_url',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_winner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
