# Generated by Django 4.2 on 2023-05-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_game_complete_game_game_url_game_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_image',
            field=models.ImageField(default='tournamentLogo/default.png', upload_to='tournamentLogo'),
        ),
    ]
