# Generated by Django 4.2 on 2023-05-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='game_vip',
            field=models.BooleanField(default=False),
        ),
    ]
