# Generated by Django 4.2 on 2023-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_game_game_paid_game_game_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_complete',
            field=models.BooleanField(default=False),
        ),
    ]
