# Generated by Django 4.2 on 2023-05-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_game_game_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='admin_winner_choice',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
