# Generated by Django 4.2 on 2023-05-31 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_admingame'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_game_odd', models.FloatField(blank=True, default=0.0, null=True)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('prediction', models.CharField(default='', max_length=255)),
                ('game_year', models.IntegerField(default=2023, null=True)),
                ('game_month', models.IntegerField(default=5, null=True)),
                ('game_date', models.IntegerField(default=26, null=True)),
                ('game_hour', models.IntegerField(default=22, null=True)),
                ('game_minute', models.IntegerField(default=18, null=True)),
                ('game_first_half_result', models.CharField(default='-', max_length=255)),
                ('game_second_half_result', models.CharField(default='-', max_length=255)),
                ('result', models.CharField(choices=[('won', 'won'), ('lost', 'lost'), ('waiting', 'waiting')], default='won', max_length=200)),
                ('game_paid', models.BooleanField(default=False, null=True)),
                ('game_competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.competition')),
            ],
        ),
        migrations.CreateModel(
            name='SportPesaJackpotGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_game_odd', models.FloatField(blank=True, default=0.0, null=True)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('prediction', models.CharField(default='', max_length=255)),
                ('game_year', models.IntegerField(default=2023, null=True)),
                ('game_month', models.IntegerField(default=5, null=True)),
                ('game_date', models.IntegerField(default=26, null=True)),
                ('game_hour', models.IntegerField(default=22, null=True)),
                ('game_minute', models.IntegerField(default=18, null=True)),
                ('game_first_half_result', models.CharField(default='-', max_length=255)),
                ('game_second_half_result', models.CharField(default='-', max_length=255)),
                ('result', models.CharField(choices=[('won', 'won'), ('lost', 'lost'), ('waiting', 'waiting')], default='won', max_length=200)),
                ('game_paid', models.BooleanField(default=False, null=True)),
                ('game_competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.competition')),
            ],
        ),
        migrations.CreateModel(
            name='FixedMatchGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_game_odd', models.FloatField(blank=True, default=0.0, null=True)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('prediction', models.CharField(default='', max_length=255)),
                ('game_year', models.IntegerField(default=2023, null=True)),
                ('game_month', models.IntegerField(default=5, null=True)),
                ('game_date', models.IntegerField(default=26, null=True)),
                ('game_hour', models.IntegerField(default=22, null=True)),
                ('game_minute', models.IntegerField(default=18, null=True)),
                ('game_first_half_result', models.CharField(default='-', max_length=255)),
                ('game_second_half_result', models.CharField(default='-', max_length=255)),
                ('result', models.CharField(choices=[('won', 'won'), ('lost', 'lost'), ('waiting', 'waiting')], default='won', max_length=200)),
                ('game_paid', models.BooleanField(default=False, null=True)),
                ('game_competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.competition')),
            ],
        ),
        migrations.CreateModel(
            name='BetikaJackpotGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_game_odd', models.FloatField(blank=True, default=0.0, null=True)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('prediction', models.CharField(default='', max_length=255)),
                ('game_year', models.IntegerField(default=2023, null=True)),
                ('game_month', models.IntegerField(default=5, null=True)),
                ('game_date', models.IntegerField(default=26, null=True)),
                ('game_hour', models.IntegerField(default=22, null=True)),
                ('game_minute', models.IntegerField(default=18, null=True)),
                ('game_first_half_result', models.CharField(default='-', max_length=255)),
                ('game_second_half_result', models.CharField(default='-', max_length=255)),
                ('result', models.CharField(choices=[('won', 'won'), ('lost', 'lost'), ('waiting', 'waiting')], default='won', max_length=200)),
                ('game_paid', models.BooleanField(default=False, null=True)),
                ('game_competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.competition')),
            ],
        ),
    ]
