# Generated by Django 4.2 on 2023-06-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_subscriptiongame_sportpesajackpotgame_fixedmatchgame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admingame',
            name='away_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='admingame',
            name='draw_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='admingame',
            name='home_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='betikajackpotgame',
            name='away_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='betikajackpotgame',
            name='draw_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='betikajackpotgame',
            name='home_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fixedmatchgame',
            name='away_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fixedmatchgame',
            name='draw_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fixedmatchgame',
            name='home_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sportpesajackpotgame',
            name='away_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sportpesajackpotgame',
            name='draw_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sportpesajackpotgame',
            name='home_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiongame',
            name='away_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiongame',
            name='draw_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiongame',
            name='home_odd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
