# Generated by Django 4.2 on 2023-06-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_admingame_away_odd_admingame_draw_odd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admingame',
            name='comments',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='betikajackpotgame',
            name='comments',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedmatchgame',
            name='comments',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sportpesajackpotgame',
            name='comments',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiongame',
            name='comments',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
